### ISSUE TITLE
Внести изменения

### ISSUE THREAD

**Issue by imirrori** [ilginzburg/work#1]
https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/1/hello/main.cpp#L4
Слишком много пустых строк. Оставляй по 1, если требуется.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/1/list/main.cpp#L4
Нужно поправить выравнивание и убрать пустые строки.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/2/formula/main.cpp#L1
Это не отсюда

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/2/formula/main.cpp#L17
Лишний пробел внутри строки

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/2/max_area/main.cpp#L34
Слишком запутанно и не читаемо.
Создай 3 переменные (площади) и по ним уже проверь. Сечас я вижу дублирование кода подсчета площади (a*a*(sqrt(3)/4)) 

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/dec_to_bin/main.cpp#L19
не вижу необходимости в этой переменной.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/dec_to_bin/main.cpp#L21
Почему то ниже ты используешь *=, а тут bin = bin + ... Давай как то единообразно.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/dec_to_bin/main.cpp#L6
Пустые строки не сделают код более читаемым, лучше к ним не привыкать.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/digits/main.cpp#L16
Сложно по вычислениям. В цикле и умножение и деление. Можно обойтись одним делением.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/leastcdiv/main.cpp#L23
выравнивание куда то поехало

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/leastcdiv/main.cpp#L33
А ноль натуральное число?

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/swap/main.cpp#L5
Что то эта программа не работает для двузначных чисел

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/series/main.cpp#L26
Что это за число? Оно не нужно для решения задания. Нужно идти по ряду, пока следующая итераци не будет меньше точности.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/series/main.cpp#L36
Не надо делать отдельный if. ПРосто подсчитай первый шаг до цикла.

https://github.com/ilginzburg/work/blob/be48e9f68039d96133abf0d818e07d3fbeaa2075/3/series/main.cpp#L40
1 = 1
1 * 2 * 1 = 2
2 * 2 * 2 = 8
Что то тут не то.

**Comment by ilginzburg** [comment]
Исправил.
